"""Kolmogorov atmospheric phase screens (FFT method).

A random phase screen with the Kolmogorov power spectrum

    PSD_phi(f) = 0.023 * r0^(-5/3) * f^(-11/3)      [f in cycles/m]

is generated by filtering white Gaussian noise in the Fourier domain. The screen
is returned in radians of phase and has statistics set by the Fried parameter r0
(in the same length units as the sampling spacing dx).

Note: the plain FFT method under-represents the lowest spatial frequencies
(tip/tilt/focus are biased low) because the period equals the screen size. This
is a known limitation; subharmonic augmentation is a later refinement. The r0
estimator deliberately works from mid-order modes to reduce sensitivity to it.

A frozen-flow (Taylor hypothesis) sequence is also provided: a large screen is
translated across the pupil at a fixed wind speed to produce a time series.
"""
from __future__ import annotations

import numpy as np


def kolmogorov_screen(
    npix: int, dx: float, r0: float, rng: np.random.Generator | None = None
) -> np.ndarray:
    """Generate one Kolmogorov phase screen of shape (npix, npix), in radians."""
    if rng is None:
        rng = np.random.default_rng()
    del_f = 1.0 / (npix * dx)  # frequency-grid spacing [cycles/m]
    fx = np.fft.fftfreq(npix, d=dx)
    fxx, fyy = np.meshgrid(fx, fx)
    f = np.sqrt(fxx ** 2 + fyy ** 2)
    f[0, 0] = 1.0  # avoid div-by-zero; DC term zeroed below

    psd = 0.023 * r0 ** (-5.0 / 3.0) * f ** (-11.0 / 3.0)
    psd[0, 0] = 0.0  # no piston

    cn = (rng.standard_normal((npix, npix)) + 1j * rng.standard_normal((npix, npix)))
    cn *= np.sqrt(psd) * del_f
    screen = np.real(np.fft.ifft2(cn)) * npix ** 2
    return screen


def frozen_flow_sequence(
    npix: int,
    dx: float,
    r0: float,
    n_frames: int,
    wind_speed: float,
    dt: float,
    rng: np.random.Generator | None = None,
):
    """Yield `n_frames` phase screens of a single screen drifting at wind_speed.

    The wind translates the screen horizontally by wind_speed * dt each frame
    (Taylor's frozen-turbulence hypothesis). A wider screen is generated so the
    pupil window never runs off the edge.
    """
    if rng is None:
        rng = np.random.default_rng()
    shift_per_frame = wind_speed * dt / dx  # [pixels/frame]
    pad = int(np.ceil(shift_per_frame * n_frames)) + 2
    big_size = _next_even(npix + pad)
    if big_size > 4096:
        raise ValueError(
            f"frozen-flow screen would be {big_size}px: wind*dt/dx*n_frames is too "
            f"large. Reduce dt or n_frames (need fine sampling: dt << tau0)."
        )
    big = kolmogorov_screen(big_size, dx, r0, rng)
    for k in range(n_frames):
        x0 = int(round(k * shift_per_frame))
        yield big[:npix, x0 : x0 + npix]


def _next_even(n: int) -> int:
    return n if n % 2 == 0 else n + 1
